# First Dataset

In [1]:
import pandas as pd

df = pd.read_csv('Datasets/Final_Train_Data.csv')

In [2]:
df.head()

,Unnamed: 0,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweat sweating increased,palpitation,...,prodrome,hypoproteinemia,alcohol binge episode,abdomen acute,air fluid level,catching breath,large-for-dates fetus,immobile,homicidal thoughts,prognosis
0,0,0,1,0,0,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,hypertensive disease
1,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,diabetes
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"depression mental , depressive disorder"
3,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,"coronary arteriosclerosis ,coronary heart disease"
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,pneumonia

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2564 entries, 0 to 2563
Columns: 402 entries, Unnamed: 0 to prognosis
dtypes: int64(401), object(1)
memory usage: 7.9+ MB

In [4]:
df['prognosis'].value_counts()

prognosis
upper respiratory infection    43
bipolar disorder               43
anxiety state                  37
psychotic disorder             37
chronic kidney failure         34
                               ..
affect labile                   9
kidney disease                  7
migraine disorders              7
pancytopenia                    7
decubitus ulcer                 3
Name: count, Length: 133, dtype: int64

In [5]:
df['Unnamed: 0'].value_counts()

Unnamed: 0
0    2564
Name: count, dtype: int64

In [6]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df.head()

,pain chest,shortness of breath,dizziness,asthenia,fall,syncope,vertigo,sweat sweating increased,palpitation,nausea,...,prodrome,hypoproteinemia,alcohol binge episode,abdomen acute,air fluid level,catching breath,large-for-dates fetus,immobile,homicidal thoughts,prognosis
0,0,1,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,hypertensive disease
1,0,1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,diabetes
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"depression mental , depressive disorder"
3,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,"coronary arteriosclerosis ,coronary heart disease"
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,pneumonia

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2564 entries, 0 to 2563
Columns: 401 entries, pain chest to prognosis
dtypes: int64(400), object(1)
memory usage: 7.8+ MB

In [8]:
df.isnull().sum()

pain chest               0
shortness of breath      0
dizziness                0
asthenia                 0
fall                     0
                        ..
catching breath          0
large-for-dates fetus    0
immobile                 0
homicidal thoughts       0
prognosis                0
Length: 401, dtype: int64

In [9]:
# Replace spaces in column names with underscores
df.columns = df.columns.str.replace(" ", "_")

# Iterate over the first 400 columns and modify their values
for col in df.columns[:-1]:  # Exclude the last column ('prognosis')
    df[col] = df[col].apply(lambda x: col if x == 1 else "")

In [10]:
df.head()

,pain_chest,shortness_of_breath,dizziness,asthenia,fall,syncope,vertigo,sweat_sweating_increased,palpitation,nausea,...,prodrome,hypoproteinemia,alcohol_binge_episode,abdomen_acute,air_fluid_level,catching_breath,large-for-dates_fetus,immobile,homicidal_thoughts,prognosis
0,,shortness_of_breath,,,,syncope,,sweat_sweating_increased,palpitation,,...,,,,,,,,,,hypertensive disease
1,,shortness_of_breath,,,,,,sweat_sweating_increased,,nausea,...,,,,,,,,,,diabetes
2,,,,,,,,,,,...,,,,,,,,,,"depression mental , depressive disorder"
3,pain_chest,shortness_of_breath,,,,,,sweat_sweating_increased,,,...,,,,,,,,,,"coronary arteriosclerosis ,coronary heart disease"
4,,shortness_of_breath,,,,,,,,,...,,,,,,,,,,pneumonia

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2564 entries, 0 to 2563
Columns: 401 entries, pain_chest to prognosis
dtypes: object(401)
memory usage: 7.8+ MB

In [12]:
# Replace NaN values with an empty string (if necessary)
df = df.fillna("")

# Concatenate all symptoms into a single 'Symptom' column
df['Symptom'] = df.iloc[:, :-1].apply(lambda row: " ".join(row), axis=1)

C:\Users\yuvam\AppData\Local\Temp\ipykernel_188636\1899728242.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['Symptom'] = df.iloc[:, :-1].apply(lambda row: " ".join(row), axis=1)

In [13]:
df.head()

,pain_chest,shortness_of_breath,dizziness,asthenia,fall,syncope,vertigo,sweat_sweating_increased,palpitation,nausea,...,hypoproteinemia,alcohol_binge_episode,abdomen_acute,air_fluid_level,catching_breath,large-for-dates_fetus,immobile,homicidal_thoughts,prognosis,Symptom
0,,shortness_of_breath,,,,syncope,,sweat_sweating_increased,palpitation,,...,,,,,,,,,hypertensive disease,shortness_of_breath syncope sweat_sweatin...
1,,shortness_of_breath,,,,,,sweat_sweating_increased,,nausea,...,,,,,,,,,diabetes,shortness_of_breath sweat_sweating_incre...
2,,,,,,,,,,,...,,,,,,,,,"depression mental , depressive disorder",sleeplessness wo...
3,pain_chest,shortness_of_breath,,,,,,sweat_sweating_increased,,,...,,,,,,,,,"coronary arteriosclerosis ,coronary heart disease",pain_chest shortness_of_breath sweat_swea...
4,,shortness_of_breath,,,,,,,,,...,,,,,,,,,pneumonia,shortness_of_breath rale ...

In [17]:
df['Symptom'][0]

' shortness_of_breath    syncope  sweat_sweating_increased palpitation  angina_pectoris                                                                                                                                                                                                                                                                                                                                                                                                     '

In [15]:
df = df.drop(df.columns[:-2], axis=1)

In [16]:
df.head()

,prognosis,Symptom
0,hypertensive disease,shortness_of_breath syncope sweat_sweatin...
1,diabetes,shortness_of_breath sweat_sweating_incre...
2,"depression mental , depressive disorder",sleeplessness wo...
3,"coronary arteriosclerosis ,coronary heart disease",pain_chest shortness_of_breath sweat_swea...
4,pneumonia,shortness_of_breath rale ...

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2564 entries, 0 to 2563
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prognosis  2564 non-null   object
 1   Symptom    2564 non-null   object
dtypes: object(2)
memory usage: 40.2+ KB

# Second Dataset

In [19]:
df2 = pd.read_csv('Datasets/dataset.csv')
df2.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB

In [21]:
df2['Disease'].value_counts()

Disease
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy                                    120
hepatitis A                                120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
Impetigo                                   120
Name: count, dtype: int64

In [22]:
df2 = df2.fillna("")
df2['Symptom']=""
for i in range(1,18):
    df2['s']=df2["Symptom_{}".format(i)]
    df2['Symptom']=df2['Symptom']+df2['s']

In [23]:
df2.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17,Symptom,s
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,itching skin_rash nodal_skin_eruptions dischro...,
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,,skin_rash nodal_skin_eruptions dischromic _pa...,
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,,,,,,,,,,,,,,,itching nodal_skin_eruptions dischromic _patches,
3,Fungal infection,itching,skin_rash,dischromic _patches,,,,,,,,,,,,,,,itching skin_rash dischromic _patches,
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,,,,,,,,,,,,,,,itching skin_rash nodal_skin_eruptions,

In [24]:
for i in range(1,18):
    df2=df2.drop("Symptom_{}".format(i),axis=1)
df2=df2.drop("s",axis=1)

In [25]:
df2.head()

            Disease                                            Symptom
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches
3  Fungal infection              itching skin_rash dischromic _patches
4  Fungal infection             itching skin_rash nodal_skin_eruptions

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Disease  4920 non-null   object
 1   Symptom  4920 non-null   object
dtypes: object(2)
memory usage: 77.0+ KB

In [27]:
df.columns

Index(['prognosis', 'Symptom'], dtype='object')

In [28]:
df2.columns

Index(['Disease', 'Symptom'], dtype='object')

In [29]:
# Rename the 'prognosis' column in df to 'Disease'
df = df.rename(columns={'prognosis': 'Disease'})

# Concatenate the two DataFrames
combined_df = pd.concat([df, df2], axis=0, ignore_index=True)

In [30]:
combined_df.head()

,Disease,Symptom
0,hypertensive disease,shortness_of_breath syncope sweat_sweatin...
1,diabetes,shortness_of_breath sweat_sweating_incre...
2,"depression mental , depressive disorder",sleeplessness wo...
3,"coronary arteriosclerosis ,coronary heart disease",pain_chest shortness_of_breath sweat_swea...
4,pneumonia,shortness_of_breath rale ...

In [31]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7484 entries, 0 to 7483
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Disease  7484 non-null   object
 1   Symptom  7484 non-null   object
dtypes: object(2)
memory usage: 117.1+ KB

In [32]:
combined_df.to_csv('merged_symptoms_data.csv')